### ISSUE TITLE
AttributeError for user_log_dir on Mac

### ISSUE THREAD

**Issue by cdeil** [ActiveState/appdirs#66]
I'm getting this error on Python 3.5 on Mac:

```
>>> appdirs.user_log_dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.5/lib/python/site-packages/appdirs.py", line 349, in user_log_dir
    appname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

On Python 2.7 and 3.4 it looks like this:

```
>>> appdirs.user_log_dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/appdirs.py", line 349, in user_log_dir
    appname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/posixpath.py", line 79, in join
    if b.startswith(sep):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

All the other functions work for me.

**Comment by tingletech** [comment]
I got it to work when I changed my code like so:

```diff
-    pid = os.path.join(appdirs.user_data_dir(), 'monitor.pid')
-    log = os.path.join(appdirs.user_log_dir(), 'monitor.log')
+    pid = os.path.join(appdirs.user_data_dir('',''), 'monitor.pid')
+    log = os.path.join(appdirs.user_log_dir('',''), 'monitor.log')
```

**Comment by Kriskras99** [comment]
You could also change line 348 in appdirs.py from `os.path.expanduser('~/Library/Logs'), appname)` to `os.path.expanduser('~/Library/Logs', appname)`.

**Comment by Kriskras99** [comment]
Problem was that it was not checked if `appname` existed, see [50a8deb]('https://github.com/Kriskras99/appdirs/commit/50a8deb82d2af12111796b34c5e5f4838f989088').
But you should probably be using `appname` unless you are sure your files have unique names or you can handle the fact that files may already exist.
